def lockanimation():
	import os
	cls = lambda: os.system("cls")
	import time
	x = .1 #speed of animation
	y = 0	#range from left
	z = 2	#range from top (min 2 or 1)
	cls()

	print("\033[31m\n"*z+"\t"*y+"     .-::/::-.")
	time.sleep(x)
	print("\t"*y+"   .:/:-...-:/:.")
	time.sleep(x)
	print("\t"*y+"  `//-       -//`")
	time.sleep(x)
	print("\t"*y+"  -//         //-")
	time.sleep(x)
	print("\t"*y+"  -//`.-----.`//-")
	time.sleep(x)
	print("\t"*y+" `://///////////:`")
	time.sleep(x)
	print("\t"*y+" ://////-.-//////:")
	time.sleep(x)
	print("\t"*y+".//////:` `://////.")
	time.sleep(x)
	print("\t"*y+"`///////- -///////`")
	time.sleep(x)
	print("\t"*y+" -//////:`://////-")
	time.sleep(x)
	print("\t"*y+"  .:///////////:.")
	time.sleep(x)
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x*15)
	cls()
	print("\033[32m\n"*(z-1)+"\t"*y+"     .-::/::-.")
	print("\t"*y+"   .:/:-...-:/:.")
	print("\t"*y+"  `//-       -//`")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//`.-----.`")
	print("\t"*y+" `://///////////:`")
	print("\t"*y+" ://////-.-//////:")
	print("\t"*y+".//////:` `://////.")
	print("\t"*y+"`///////- -///////`")
	print("\t"*y+" -//////:`://////-")
	print("\t"*y+"  .:///////////:.")
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-::/::-.")
	print("\t"*y+"   .:/:-...-:/:.")
	print("\t"*y+"  `//-       -//`")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         ")
	print("\t"*y+"  -//`.-----.`")
	print("\t"*y+" `://///////////:`")
	print("\t"*y+" ://////-.-//////:")
	print("\t"*y+".//////:` `://////.")
	print("\t"*y+"`///////- -///////`")
	print("\t"*y+" -//////:`://////-")
	print("\t"*y+"  .:///////////:.")
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-::/::-.")
	print("\t"*y+"   .:/:-...-:/:.")
	print("\t"*y+"  `//-       -//`")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         ")
	print("\t"*y+"  -//`.-----.`")
	print("\t"*y+" `://///////////:`")
	print("\t"*y+" ://////-.-//////:")
	print("\t"*y+".//////:` `://////.")
	print("\t"*y+"`///////- -///////`")
	print("\t"*y+" -//////:`://////-")
	print("\t"*y+"  .:///////////:.")
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-::/::-.")
	print("\t"*y+"   .:/:-...-:/:.")
	print("\t"*y+"  `  -       -//`")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         ")
	print("\t"*y+"  -//`.-----.`")
	print("\t"*y+" `://///////////:`")
	print("\t"*y+" :/// //-.-//////:")
	print("\t"*y+".//////:` `://////.")
	print("\t"*y+"`///////- -/// ///`")
	print("\t"*y+" -//// /:`://////-")
	print("\t"*y+"  .:///////////:.")
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-::/::-.")
	print("\t"*y+"   .:/:-...-:/:.")
	print("\t"*y+"  `  -       -//`")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         //-")
	print("\t"*y+"  -//         ")
	print("\t"*y+"  -//`.-----.`")
	print("\t"*y+" `://///////  //:`")
	print("\t"*y+" :/// //-.-//////:")
	print("\t"*y+".//////:` `:////.")
	print("\t"*y+"`//  ///- -/// ///`")
	print("\t"*y+" -//// /:`://////-")
	print("\t"*y+"  .://  ///////:.")
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-::/::-.")
	print("\t"*y+"   .:/:-...  /:.")
	print("\t"*y+"  `  -       -//`")
	print("\t"*y+"  -//           -")
	print("\t"*y+"  -           //-")
	print("\t"*y+"  -//         ")
	print("\t"*y+"  -/   -----.`")
	print("\t"*y+" `://   ////  //:`")
	print("\t"*y+" :///   -.-//////:")
	print("\t"*y+".//////:`    ///.")
	print("\t"*y+"`//  ///- -/// ///`")
	print("\t"*y+" -//// /:`://////-")
	print("\t"*y+"  .://  ///   /:.")
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-    -.")
	print("\t"*y+"   .:/:      /:.")
	print("\t"*y+"  `  -       -//`")
	print("\t"*y+"  -//           -")
	print("\t"*y+"  -           //-")
	print("\t"*y+"  -//         ")
	print("\t"*y+"  -/   -----.`")
	print("\t"*y+" `://   ////  //:`")
	print("\t"*y+" :///   -.-/     :")
	print("\t"*y+"./     :`    ///.")
	print("\t"*y+"`//  ///- -/// ///`")
	print("\t"*y+" -//// /:`:     /-")
	print("\t"*y+"  .://  ///   /:.")
	print("\t"*y+"    `.-:///:-.`")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-    -.")
	print("\t"*y+"   .:/:         ")
	print("\t"*y+"  `  -       -//`")
	print("\t"*y+"  -//           -")
	print("\t"*y+"  -              ")
	print("\t"*y+"              ")
	print("\t"*y+"  -/        .`")
	print("\t"*y+" `://   ////  //:`")
	print("\t"*y+" :     -.-/     :")
	print("\t"*y+"./     :`    ///.")
	print("\t"*y+"`//  /    -///   /`")
	print("\t"*y+" -              /-")
	print("\t"*y+"     /  /     /:.")
	print("\t"*y+"    `  :  /:-.`")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-    -.")
	print("\t"*y+"     /:         ")
	print("\t"*y+"  `  -       -  `")
	print("\t"*y+"    /           -")
	print("\t"*y+"  -              ")
	print("\t"*y+"              ")
	print("\t"*y+"  -/        .`")
	print("\t"*y+" `  /      /   /:`")
	print("\t"*y+" :     -.-/      ")
	print("\t"*y+"./     :`      /.")
	print("\t"*y+"`    /    -/     /`")
	print("\t"*y+" -              /-")
	print("\t"*y+"     /  /     /  ")
	print("\t"*y+"    `  :  /:   ")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-    -.")
	print("\t"*y+"     /:         \n")
	print("\t"*y+"    /           -")
	print("\t"*y+"  -              ")
	print("\t"*y+"              \n")
	print("\t"*y+" `  /      /   /:`")
	print("\t"*y+" :     -.-/      ")
	print("\t"*y)
	print("\t"*y+"`    /    -/     /`")
	print("\t"*y+" -              /-")
	print("\t"*y+"     /  /     /  ")
	time.sleep(x*.6)
	cls()
	print("\n"*(z-2)+"\t"*y+"     .-    -.\n\n")
	print("\t"*y+"    /           -")
	print("\t"*y)
	print("\t"*y+"              ")
	print("\t"*y)
	print("\t"*y+" `  /      /   /:`")
	print("\t"*y)
	print("\t"*y)
	print("\t"*y)
	print("\t"*y+" -              /-")
	time.sleep(.05)
	cls()
	time.sleep(1)
while 2>1:
	lockanimation()
